//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requesttbl
    {
        public System.Guid id { get; set; }
        public string fileid { get; set; }
        public string requesttyepe { get; set; }
        public string causeofrequest { get; set; }
        public string response { get; set; }
        public string causeofresponse { get; set; }
    }
}
